### ISSUE TITLE
codepad breaks adminpads

### ISSUE THREAD

**Issue by aicm** [spcsser/ep_adminpads#28]
Hello there, 

I'm not sure why but the codepad plugin breaks adminpads. Don't know if this is an issue to post here, or in codepad.

Thanks :)

**Comment by LaKing** [comment]
You can post in both .) ...

ep_codepad is independent from ep_adminpads, I cant recall any bindings. It just installs as a dependency, as i find adminpads handy for codepad users.

No idea what could break it, and where to start looking at the code :S ...

**Comment by aicm** [comment]
Oh that may be the problem then, I had installed adminpads before installing codepad. I removed adminpads and installed codepad by itself (no other plugins) and it's doing just fine. So sorry about that, user error.

**Comment by LaKing** [comment]
Strange, I would think that that user behavior wouldn't break anything. ...

As far as I see, many things broke in codepad. Adminpads don't work even on a fresh install at the moment. The underlying software seems to change from time to time, and I need to fix tons of bugs then .. :/ ...

**Comment by aicm** [comment]
It seems to be the browser cache that gives you that impression. I bumped into the same issue and then I force refreshed a couple of times and it worked. I didn't even have to restart etherpad. I'm running the devel branch, I think my last git pull was 5 days ago.
