### ISSUE TITLE
Support etherpad subdirectory paths

### ISSUE THREAD

**Issue by lkraav** [spcsser/ep_adminpads#30]
With latest EP releases, should follow the model of https://github.com/ether/etherpad-lite/pull/2748

**Comment by Fraifrai** [comment]
I have the same problem, tables are blank if etherpad is accessed via an Apache subdirectory

**Comment by Fraifrai** [comment]
solved by this patch https://github.com/spcsser/ep_adminpads/pull/29

**Comment by spcsser** [comment]
fix by v0.0.10 just released (https://www.npmjs.com/package/ep_adminpads).
Thx to @cxcv for the patch!
