### ISSUE TITLE
Incorrect link with special characters in pad name

### ISSUE THREAD

**Issue by rugk** [spcsser/ep_adminpads#31]
I have a pad with `"` in it's name. But when I list all pads with this addon the pad name is truncated at the position of this special character.

So e.g. the pad name is `thisisa"pad`. When showing it in the "manage pads" part of the admin interface it only shows `thisisa`.

**Comment by spcsser** [comment]
Thanks for pointing this out, it's fixed with 0.0.11 (published as of now)
