### ISSUE TITLE
package.json Missing

### ISSUE THREAD

**Issue by peasead** [spcsser/ep_adminpads#35]
I'm trying to install this via `sudo npm install ep_adminpads` and I'm getting the below message and the plugin isn't being installed (according to the UI).
```
npm WARN enoent ENOENT: no such file or directory, open '/opt/etherpad/package.json'
```
Using the UI for Etherpad, I can install the plugin, but I wanted to automate this process.

Exact command
```
sudo npm install ep_adminpads
/opt/etherpad
└─┬ ep_adminpads@0.0.11
  └─┬ log4js@1.1.1
    ├─┬ debug@2.6.8
    │ └── ms@2.0.0
    ├── semver@5.3.0
    └─┬ streamroller@0.4.1
      ├── date-format@0.0.0
      ├── debug@0.7.4
      ├─┬ mkdirp@0.5.1
      │ └── minimist@0.0.8
      └─┬ readable-stream@1.1.14
        ├── core-util-is@1.0.2
        ├── inherits@2.0.3
        ├── isarray@0.0.1
        └── string_decoder@0.10.31

npm WARN enoent ENOENT: no such file or directory, open '/opt/etherpad/package.json'
```
I also tried `sudo npm install -g --save ep_adminpads`, which didn't give me the error, but Etherpad won't start after that...so I'm assuming that's not the fix.

This is on `CentOS 7.3` with npm version `3.10.10`.

**Comment by spcsser** [comment]
This is not really an issue with this plugin...
As the error message states, the directory where you try to install the node module does not contain a package.json file. If you checked out etherpad via git you could try and look under the src folder.
Hope this helps.

**Comment by peasead** [comment]
Thank you, that did resolve the error.

That said, when I run `sudo npm install ep_adminpads` and restart Etherpad, it still isn't installed until I click the "Install" button in the Plugin Manager.

Is there any other trick here?

Thanks for all the help...npm is new to me.

**Comment by spcsser** [comment]
Ok, apparently etherpad is using the package.json under node_modules/ep_etherpad-lite. Try npm installing there.
