### ISSUE TITLE
When option "editOnly" is enabled, the plugin doesn't show pads

### ISSUE THREAD

**Issue by rogierlommers** [spcsser/ep_adminpads#38]
First of all, thanks for your plugin! I like it! However, I found an issue: when option `editOnly` is set to `true`, the plugin doesn't show pads. Is this by design?

**Comment by spcsser** [comment]
Hey, thanks for your nice words!
I'm not relying on those settings. If there are no pads listed, this would indicate that the internal EPL functions are not exposing those data if editOnly is active. 
Sorry, but I'm currently not able to investigate or support you on this issue.

**Comment by rogierlommers** [comment]
Allright; thanks for the reply. I already fixed it by using this: https://github.com/rogierlommers/etherpad-cli
